add $file subs

diff --git a/git/fork b/git/fork
--- a/git/fork
+++ b/git/fork
@@ -1,11 +1,15 @@
 #!/bin/bash
 
 url="https://github.com/jarun/nnn/blob/master/Makefile"
+url="https://github.com/nvim-lua/plenary.nvim/blob/master/lua/plenary/async_lib/async.lua"
 # sed not alow to match group > 9, so bettre way is split it
+# dash - , should be at end or begin
 user_repo="$(sed -E -e 's#((git|ssh|http(s)?)|(git@[\w\.]+))(://)?(([\w\.@\:/\-~])[^/]+)(/|:)##' -e 's#(\w+)/(\w+).*#\1/\2#' <<< $url)"
 repo=${user_repo#*/}
 
+# gh repo fork https://github.com/$user_repo --clone --org ayoub-fork && cd ${repo} || echo 'error';exit
 
-echo $repo
+file="$(sed -E 's#((git|ssh|http(s)?)|(git@[a-zA-Z0-9\.]+))(://)?(([-a-zA-Z0-9\.@\:/~])[^/]+)(/|:)(([-a-zA-Z0-9\_\.])+/){4}##' <<< $url)"
 
-gh repo fork https://github.com/$user_repo --clone --org ayoub-fork && cd ${repo} || echo 'error';exit
+echo $file
+# echo nvim 
